# Generated by Django 4.0 on 2023-03-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
