# Generated by Django 4.0 on 2023-03-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_comment_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='view_count',
        ),
    ]
